### ISSUE TITLE
IE11 = doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by mourtazag** [SmashingQuasar/easy-masonry#4]
`EasyMasonry.prototype.removeBaseElements = function () {
            Array.prototype.forEach.call(this.elements, function (element) {
                //element.remove(); // Replaced by below
                element.parentNode.removeChild(element);
            });
   };`

**Comment by mourtazag** [comment]
On line 105

**Comment by SmashingQuasar** [comment]
Requires a polyfill to work.
